[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "D4qTif2KUt5cKot4RVn1kSxPiXaryKvBJDWbuBLsVybL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/xavierjones/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
