[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "9PdTiPTE9NaujVAW6mA5USf5ZeC3xMCDwBBthNL3dGD5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/xavierjones/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
